### PR TITLE
Add 1.4-rc1 to beta

### LINKED ISSUE #25: push 1.4-rc into beta channel
Hey, would be nice to be able test new 3D features of STK 1.4! Thank you

### PR DESCRIPTION
**Pull request by jibsaramnim**
- Resolves #25

I tried to follow whatever was already in this repository, but please let me know if I missed anything :).

### CODE REVIEW

**Comment by jibsaramnim** [comment]
Works as expected on two of my systems using the above test build install :)

image

**Comment by AsciiWolf** [comment]
Thanks! Any chance you could remove the "Revert runtime-version and config-opts changes." commit? It does not seem correct.

**Comment by jibsaramnim** [comment]
Hi @AsciiWolf! Thank you for taking a look, and apologies for not having merged master into this myself. I had based my changes off of the `beta` branch and as they looked so different I wasn't sure if I should've done that.

I have rebased off of master, though as you already noticed, my initial runtime and config-opts revert really wasn't necessary, so I've reverted that commit as you suggested too. I must admit that Git's rebase logic always confuses me, so please let me know if I have made any mistakes there, and/or if I missed anything else. There seem to be some merge conflicts now, I am not sure if that's my doing or just because the `beta` branch was so different from `master` already?

I have removed the screenshots patch as this [no longer seems needed](https://github.com/supertuxkart/stk-code/blob/master/data/supertuxkart.appdata.xml#L156) with more recent versions of STK.

Many thanks!

**Comment by jibsaramnim** [comment]
I've also removed cacert patch as that no longer seems necessary either (Based on https://github.com/supertuxkart/stk-code/commit/9bf537ab351f165555048fbc5df88193d8cd70f2, and the build bot noticing it appearing like a reverse patch instead).

**Comment by jibsaramnim** [comment]
Confirmed that the above test build installs successfully on my main machine!

**Comment by AsciiWolf** [comment]
Thanks! The final 1.4 STK was however released today. I will update the master branch and sync the beta branch with it so there won't be any merge conflicts with beta in the future. Thanks again for your PR. I am going to close it now, but feel free to send new PRs, they are highly appreciated (since I am usually the only active contributor)!

**Pull request closed without merging**
